# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.26.1/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.26.1/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/nekotoxin/workspace/Projects/MultiUser-secondFileSystem

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/nekotoxin/workspace/Projects/MultiUser-secondFileSystem

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.26.1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.26.1/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/nekotoxin/workspace/Projects/MultiUser-secondFileSystem/CMakeFiles /Users/nekotoxin/workspace/Projects/MultiUser-secondFileSystem//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/nekotoxin/workspace/Projects/MultiUser-secondFileSystem/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SecondLevelFS

# Build rule for target.
SecondLevelFS: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SecondLevelFS
.PHONY : SecondLevelFS

# fast build rule for target.
SecondLevelFS/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecondLevelFS.dir/build.make CMakeFiles/SecondLevelFS.dir/build
.PHONY : SecondLevelFS/fast

BufferManager.o: BufferManager.cpp.o
.PHONY : BufferManager.o

# target to build an object file
BufferManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecondLevelFS.dir/build.make CMakeFiles/SecondLevelFS.dir/BufferManager.cpp.o
.PHONY : BufferManager.cpp.o

BufferManager.i: BufferManager.cpp.i
.PHONY : BufferManager.i

# target to preprocess a source file
BufferManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecondLevelFS.dir/build.make CMakeFiles/SecondLevelFS.dir/BufferManager.cpp.i
.PHONY : BufferManager.cpp.i

BufferManager.s: BufferManager.cpp.s
.PHONY : BufferManager.s

# target to generate assembly for a file
BufferManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecondLevelFS.dir/build.make CMakeFiles/SecondLevelFS.dir/BufferManager.cpp.s
.PHONY : BufferManager.cpp.s

File.o: File.cpp.o
.PHONY : File.o

# target to build an object file
File.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecondLevelFS.dir/build.make CMakeFiles/SecondLevelFS.dir/File.cpp.o
.PHONY : File.cpp.o

File.i: File.cpp.i
.PHONY : File.i

# target to preprocess a source file
File.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecondLevelFS.dir/build.make CMakeFiles/SecondLevelFS.dir/File.cpp.i
.PHONY : File.cpp.i

File.s: File.cpp.s
.PHONY : File.s

# target to generate assembly for a file
File.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecondLevelFS.dir/build.make CMakeFiles/SecondLevelFS.dir/File.cpp.s
.PHONY : File.cpp.s

FileManager.o: FileManager.cpp.o
.PHONY : FileManager.o

# target to build an object file
FileManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecondLevelFS.dir/build.make CMakeFiles/SecondLevelFS.dir/FileManager.cpp.o
.PHONY : FileManager.cpp.o

FileManager.i: FileManager.cpp.i
.PHONY : FileManager.i

# target to preprocess a source file
FileManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecondLevelFS.dir/build.make CMakeFiles/SecondLevelFS.dir/FileManager.cpp.i
.PHONY : FileManager.cpp.i

FileManager.s: FileManager.cpp.s
.PHONY : FileManager.s

# target to generate assembly for a file
FileManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecondLevelFS.dir/build.make CMakeFiles/SecondLevelFS.dir/FileManager.cpp.s
.PHONY : FileManager.cpp.s

FileSystem.o: FileSystem.cpp.o
.PHONY : FileSystem.o

# target to build an object file
FileSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecondLevelFS.dir/build.make CMakeFiles/SecondLevelFS.dir/FileSystem.cpp.o
.PHONY : FileSystem.cpp.o

FileSystem.i: FileSystem.cpp.i
.PHONY : FileSystem.i

# target to preprocess a source file
FileSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecondLevelFS.dir/build.make CMakeFiles/SecondLevelFS.dir/FileSystem.cpp.i
.PHONY : FileSystem.cpp.i

FileSystem.s: FileSystem.cpp.s
.PHONY : FileSystem.s

# target to generate assembly for a file
FileSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecondLevelFS.dir/build.make CMakeFiles/SecondLevelFS.dir/FileSystem.cpp.s
.PHONY : FileSystem.cpp.s

Inode.o: Inode.cpp.o
.PHONY : Inode.o

# target to build an object file
Inode.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecondLevelFS.dir/build.make CMakeFiles/SecondLevelFS.dir/Inode.cpp.o
.PHONY : Inode.cpp.o

Inode.i: Inode.cpp.i
.PHONY : Inode.i

# target to preprocess a source file
Inode.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecondLevelFS.dir/build.make CMakeFiles/SecondLevelFS.dir/Inode.cpp.i
.PHONY : Inode.cpp.i

Inode.s: Inode.cpp.s
.PHONY : Inode.s

# target to generate assembly for a file
Inode.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecondLevelFS.dir/build.make CMakeFiles/SecondLevelFS.dir/Inode.cpp.s
.PHONY : Inode.cpp.s

Machine.o: Machine.cpp.o
.PHONY : Machine.o

# target to build an object file
Machine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecondLevelFS.dir/build.make CMakeFiles/SecondLevelFS.dir/Machine.cpp.o
.PHONY : Machine.cpp.o

Machine.i: Machine.cpp.i
.PHONY : Machine.i

# target to preprocess a source file
Machine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecondLevelFS.dir/build.make CMakeFiles/SecondLevelFS.dir/Machine.cpp.i
.PHONY : Machine.cpp.i

Machine.s: Machine.cpp.s
.PHONY : Machine.s

# target to generate assembly for a file
Machine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecondLevelFS.dir/build.make CMakeFiles/SecondLevelFS.dir/Machine.cpp.s
.PHONY : Machine.cpp.s

OpenFileManager.o: OpenFileManager.cpp.o
.PHONY : OpenFileManager.o

# target to build an object file
OpenFileManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecondLevelFS.dir/build.make CMakeFiles/SecondLevelFS.dir/OpenFileManager.cpp.o
.PHONY : OpenFileManager.cpp.o

OpenFileManager.i: OpenFileManager.cpp.i
.PHONY : OpenFileManager.i

# target to preprocess a source file
OpenFileManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecondLevelFS.dir/build.make CMakeFiles/SecondLevelFS.dir/OpenFileManager.cpp.i
.PHONY : OpenFileManager.cpp.i

OpenFileManager.s: OpenFileManager.cpp.s
.PHONY : OpenFileManager.s

# target to generate assembly for a file
OpenFileManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecondLevelFS.dir/build.make CMakeFiles/SecondLevelFS.dir/OpenFileManager.cpp.s
.PHONY : OpenFileManager.cpp.s

SecondFileKernel.o: SecondFileKernel.cpp.o
.PHONY : SecondFileKernel.o

# target to build an object file
SecondFileKernel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecondLevelFS.dir/build.make CMakeFiles/SecondLevelFS.dir/SecondFileKernel.cpp.o
.PHONY : SecondFileKernel.cpp.o

SecondFileKernel.i: SecondFileKernel.cpp.i
.PHONY : SecondFileKernel.i

# target to preprocess a source file
SecondFileKernel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecondLevelFS.dir/build.make CMakeFiles/SecondLevelFS.dir/SecondFileKernel.cpp.i
.PHONY : SecondFileKernel.cpp.i

SecondFileKernel.s: SecondFileKernel.cpp.s
.PHONY : SecondFileKernel.s

# target to generate assembly for a file
SecondFileKernel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecondLevelFS.dir/build.make CMakeFiles/SecondLevelFS.dir/SecondFileKernel.cpp.s
.PHONY : SecondFileKernel.cpp.s

User.o: User.cpp.o
.PHONY : User.o

# target to build an object file
User.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecondLevelFS.dir/build.make CMakeFiles/SecondLevelFS.dir/User.cpp.o
.PHONY : User.cpp.o

User.i: User.cpp.i
.PHONY : User.i

# target to preprocess a source file
User.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecondLevelFS.dir/build.make CMakeFiles/SecondLevelFS.dir/User.cpp.i
.PHONY : User.cpp.i

User.s: User.cpp.s
.PHONY : User.s

# target to generate assembly for a file
User.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecondLevelFS.dir/build.make CMakeFiles/SecondLevelFS.dir/User.cpp.s
.PHONY : User.cpp.s

UserManager.o: UserManager.cpp.o
.PHONY : UserManager.o

# target to build an object file
UserManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecondLevelFS.dir/build.make CMakeFiles/SecondLevelFS.dir/UserManager.cpp.o
.PHONY : UserManager.cpp.o

UserManager.i: UserManager.cpp.i
.PHONY : UserManager.i

# target to preprocess a source file
UserManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecondLevelFS.dir/build.make CMakeFiles/SecondLevelFS.dir/UserManager.cpp.i
.PHONY : UserManager.cpp.i

UserManager.s: UserManager.cpp.s
.PHONY : UserManager.s

# target to generate assembly for a file
UserManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecondLevelFS.dir/build.make CMakeFiles/SecondLevelFS.dir/UserManager.cpp.s
.PHONY : UserManager.cpp.s

main_multi.o: main_multi.cpp.o
.PHONY : main_multi.o

# target to build an object file
main_multi.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecondLevelFS.dir/build.make CMakeFiles/SecondLevelFS.dir/main_multi.cpp.o
.PHONY : main_multi.cpp.o

main_multi.i: main_multi.cpp.i
.PHONY : main_multi.i

# target to preprocess a source file
main_multi.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecondLevelFS.dir/build.make CMakeFiles/SecondLevelFS.dir/main_multi.cpp.i
.PHONY : main_multi.cpp.i

main_multi.s: main_multi.cpp.s
.PHONY : main_multi.s

# target to generate assembly for a file
main_multi.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecondLevelFS.dir/build.make CMakeFiles/SecondLevelFS.dir/main_multi.cpp.s
.PHONY : main_multi.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... SecondLevelFS"
	@echo "... BufferManager.o"
	@echo "... BufferManager.i"
	@echo "... BufferManager.s"
	@echo "... File.o"
	@echo "... File.i"
	@echo "... File.s"
	@echo "... FileManager.o"
	@echo "... FileManager.i"
	@echo "... FileManager.s"
	@echo "... FileSystem.o"
	@echo "... FileSystem.i"
	@echo "... FileSystem.s"
	@echo "... Inode.o"
	@echo "... Inode.i"
	@echo "... Inode.s"
	@echo "... Machine.o"
	@echo "... Machine.i"
	@echo "... Machine.s"
	@echo "... OpenFileManager.o"
	@echo "... OpenFileManager.i"
	@echo "... OpenFileManager.s"
	@echo "... SecondFileKernel.o"
	@echo "... SecondFileKernel.i"
	@echo "... SecondFileKernel.s"
	@echo "... User.o"
	@echo "... User.i"
	@echo "... User.s"
	@echo "... UserManager.o"
	@echo "... UserManager.i"
	@echo "... UserManager.s"
	@echo "... main_multi.o"
	@echo "... main_multi.i"
	@echo "... main_multi.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

